export enum ChatMessageStatus {
  PENDING = 0,
  DELIVERED = 1,
  READ = 2
}

export enum MessageTypeId {
  NORMAL_MESSAGE = 1,
  VOICE_CALL_START_MESSAGE = 2,
  VOICE_CALL_END_MESSAGE = 3,
  VIDEO_CALL_START_MESSAGE = 4,
  VIDEO_CALL_END_MESSAGE = 5,
  VOICE_CALLING_MESSAGE = 6,
  VIDEO_CALLING_MESSAGE = 7,
  VOICE_CALL_REJECTED = 8,
  VIDEO_CALL_REJECTED = 9,
  VOICE_CALL_MISSED_BY_SENDER = 10,
  VIDEO_CALL_MISSED_BY_SENDER = 11,
  VOICE_CALL_MISSED_BY_RECEIVER = 12,
  VIDEO_CALL_MISSED_BY_RECEIVER = 13,
  FILE = 14
}
