export enum LookupTypes {
  ALLERGY = 'allergy',
  ALLERGY_REACTION = 'allergyReaction',
  APPOINTMENT_STATUS = 'appointmentStatus',
  BOOSTER = 'booster',
  CONSULTATION_STATUS = 'consultationStatus',
  DIAGNOSIS = 'diagnosis',
  DISEASE = 'disease',
  GENDER = 'gender',
  FAMILY_RELATION = 'familyRelation',
  SPECIALITY = 'speciality',
  SUB_VITAL_SIGN = 'subVitalSign',
  SURGERY = 'surgery',
  SYMPTOM = 'symptom',
  USER_STATUS = 'userStatus',
  VACCINATION = 'vaccination',
  VITAL_SIGN = 'vitalSign',
  COUNTRY = 'country',
  STATE = 'state',
  MARITAL_STATUS = 'maritalStatus',
  BLOOD_GROUP = 'bloodGroup',
  DEPARTMENT = 'department'
}
