export enum NOTIFICATIONS {
    BOOK_APPOINTMENT = 'BOOK_APPOINTMENT',
    PRESCRIPTION = 'PRESCRIPTION',
    FORUM_ANSWER = 'FORUM_ANSWER',
    INSTANT_REQUEST_REJECT = 'INSTANT_REQUEST_REJECT',
    APPOINTMENT_CANCEL = 'APPOINTMENT_CANCEL',
    DROP_CONSULTATION = 'DROP_CONSULTATION',
}
